import { lstatSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { RELEASE_UNITS } from "./units.mjs";

export const COMPATIBILITY_PATH = "docs/reference/compatibility.md";
const INVALID = "Compatibility document is invalid";
const MAX_BYTES = 256 * 1024;
const CONTRACT_NAMES = Object.freeze({ protocol: "adapter protocol", widgetChannel: "widget channel" });
const HEADER = Object.freeze([
  "# Compatibility",
  "",
  "<!-- Generated by pnpm release:prepare from scripts/release/units.mjs. Do not edit by hand. -->",
  "",
  "The application and the packages agree on versioned runtime contracts: the",
  "adapter protocol major (`protocolVersion` 1.x, checked by `dashboard-client`)",
  "with its profiles and capabilities (`tc-*@1`), and the widget channel",
  "(`WIDGET_CHANNEL_VERSION`). Each row records a unit's current released version",
  "and the contract majors it implements; the `gauntlet` row records the majors",
  "the application supports. A package works with an application release that",
  "supports every major the package implements. Release preparation rewrites the",
  "rows of the units it releases and rejects a plan that would break this rule.",
  "",
  "| Unit | Version | Implements | Supports |",
  "| --- | --- | --- | --- |",
].join("\n"));
const ROW = /^\| `([a-z0-9-]+)` \| (\d+\.\d+\.\d+) \| ([^|]+) \| ([^|]+) \|$/u;

const freezeSupports = (supports) => Object.freeze(Object.fromEntries(
  Object.entries(supports).map(([contract, majors]) => [contract, Object.freeze([...majors])]),
));
const sameContracts = (left, right) => JSON.stringify(Object.entries(left).sort()) === JSON.stringify(Object.entries(right).sort());

export function catalogEntry(unit, version) {
  return Object.freeze({
    id: unit.id,
    version,
    implements: Object.freeze({ ...(unit.contracts.implements ?? {}) }),
    supports: freezeSupports(unit.contracts.supports ?? {}),
  });
}

export function catalogEntries(versions, catalog = RELEASE_UNITS) {
  return Object.freeze(catalog.map((unit) => catalogEntry(unit, versions.get(unit.id))));
}

const formatImplements = (map) => (Object.keys(map).length === 0 ? "none" : Object.entries(map).map(([key, major]) => `${key} ${major}`).join("; "));
const formatSupports = (map) => (Object.keys(map).length === 0 ? "none" : Object.entries(map).map(([key, majors]) => `${key} ${majors.join(", ")}`).join("; "));

function parseCell(cell, multiple) {
  if (cell === "none") return {};
  return Object.fromEntries(cell.split("; ").map((part) => {
    const match = (multiple ? /^([A-Za-z]+) ([1-9][0-9]*(?:, [1-9][0-9]*)*)$/u : /^([A-Za-z]+) ([1-9][0-9]*)$/u).exec(part);
    if (match === null) throw new Error(INVALID);
    return [match[1], multiple ? match[2].split(", ").map(Number) : Number(match[2])];
  }));
}

export function renderCompatibilityDocument(entries) {
  const rows = entries.map(({ id, version, implements: implemented, supports }) =>
    `| \`${id}\` | ${version} | ${formatImplements(implemented)} | ${formatSupports(supports)} |`);
  return `${HEADER}\n${rows.join("\n")}\n`;
}

export function parseCompatibilityDocument(source) {
  if (typeof source !== "string" || !source.startsWith(`${HEADER}\n`) || !source.endsWith("\n")) throw new Error(INVALID);
  const rows = source.slice(HEADER.length + 1, -1).split("\n");
  if (rows.length !== RELEASE_UNITS.length) throw new Error(INVALID);
  return Object.freeze(rows.map((row, index) => {
    const match = ROW.exec(row);
    if (match === null || match[1] !== RELEASE_UNITS[index].id) throw new Error(INVALID);
    return Object.freeze({
      id: match[1],
      version: match[2],
      implements: Object.freeze(parseCell(match[3], false)),
      supports: freezeSupports(parseCell(match[4], true)),
    });
  }));
}

export function readCompatibilityDocument(root) {
  const path = resolve(root, COMPATIBILITY_PATH);
  const stat = lstatSync(path);
  if (!stat.isFile() || stat.size > MAX_BYTES) throw new Error(INVALID);
  return parseCompatibilityDocument(readFileSync(path, "utf8"));
}

export function updateCompatibilityEntries(recorded, plan, catalog = RELEASE_UNITS) {
  const planned = new Map(plan.units.map(({ id, to }) => [id, to]));
  return Object.freeze(catalog.map((unit) => {
    if (planned.has(unit.id)) return catalogEntry(unit, planned.get(unit.id));
    const row = recorded.find(({ id }) => id === unit.id);
    if (row === undefined) throw new Error(INVALID);
    return row;
  }));
}

export function compatibilityProblems(plan, recorded, catalog = RELEASE_UNITS) {
  const problems = [];
  const planned = new Map(plan.units.map(({ id, to }) => [id, to]));
  const rows = new Map(recorded.map((entry) => [entry.id, entry]));
  const application = catalog.find(({ id }) => id === "gauntlet");
  const releasedApplication = rows.get("gauntlet");
  if (application === undefined || releasedApplication === undefined) throw new Error(INVALID);
  let supports = releasedApplication.supports;
  let applicationVersion = releasedApplication.version;
  if (planned.has("gauntlet")) {
    supports = application.contracts.supports ?? {};
    applicationVersion = planned.get("gauntlet");
  } else if (!sameContracts(application.contracts.supports ?? {}, releasedApplication.supports)) {
    problems.push("gauntlet: its supported contracts changed without a gauntlet release");
  }
  for (const unit of catalog) {
    if (unit.id === "gauntlet") continue;
    const row = rows.get(unit.id);
    if (row === undefined) throw new Error(INVALID);
    let implemented = unit.contracts.implements ?? {};
    if (!planned.has(unit.id)) {
      if (!sameContracts(implemented, row.implements)) problems.push(`${unit.id}: its implemented contracts changed without a ${unit.id} release`);
      implemented = row.implements;
    }
    for (const [contract, major] of Object.entries(implemented)) {
      if (!(supports[contract] ?? []).includes(major)) {
        problems.push(`${unit.id}: implements ${contract} ${major}, which gauntlet ${applicationVersion} does not support`);
      }
    }
  }
  return problems;
}

const describe = (contract, majors) => `${CONTRACT_NAMES[contract] ?? contract} ${majors.join(", ")}`;

export function compatibilityLine(unitId, entries) {
  const entry = entries.find(({ id }) => id === unitId);
  const application = entries.find(({ id }) => id === "gauntlet");
  if (entry === undefined || application === undefined) throw new Error(INVALID);
  const supported = Object.entries(application.supports).map(([contract, majors]) => describe(contract, majors)).join(" and ");
  if (unitId === "gauntlet") return `Compatibility: Gauntlet ${entry.version} supports ${supported}.`;
  const implemented = Object.entries(entry.implements).map(([contract, major]) => describe(contract, [major]));
  if (implemented.length === 0) return `Compatibility: ${unitId} ${entry.version} has no versioned runtime contract with the application.`;
  return `Compatibility: ${unitId} ${entry.version} implements ${implemented.join(" and ")}; Gauntlet ${application.version} supports ${supported}.`;
}

export function compatibilityDocumentProblems(source, versions) {
  let entries;
  try {
    entries = parseCompatibilityDocument(source);
  } catch {
    return [`${COMPATIBILITY_PATH} is not a generated compatibility document`];
  }
  return entries.filter(({ id, version }) => versions.get(id) !== version)
    .map(({ id, version }) => `${COMPATIBILITY_PATH}: ${id} is recorded at ${version} but its manifest version is ${versions.get(id)}`);
}
