apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gauntlet.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "gauntlet.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ include "gauntlet.configuration" . | indent 4 }}
